apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-s3
  resources:
    requests:
      storage: 5Gi
