apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messenger-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # ЗАМЕНИТЕ на адрес вашего GitHub-репозитория
    repoURL: https://github.com/evdakCherpak/k8s_laba
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: messenger-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
